### ISSUE TITLE
Passing strings from and to lua

### ISSUE THREAD

**Issue by alubbe** [alexcrichton/rust-ffi-examples#10]
I have been trying to adapt the example https://github.com/alexcrichton/rust-ffi-examples/blob/master/luajit-to-rust/src/lib.rs to use strings instead of i32s.

```
pub extern fn really_useful_string_transformation(subject: &str) -> &str {
  return subject;
}

//lua
  ffi.cdef[[
  const char* really_useful_string_transformation(const char* subject);
  ]]
  local really_useful_string_transformation = ffi.load('...').really_useful_string_transformation
  ngx.say(ffi.string(really_useful_string_transformation("peter")))
```

This works, but if I want to transform `subject`, I need to return `String` in rust instead of the pointer. But what is the corresponding return type that I declare in lua?

```
pub extern fn really_useful_string_transformation(subject: &str) -> String {
  return subject.to_string();
}

//lua
  ffi.cdef[[
  const --WHAT GOES HERE?-- really_useful_string_transformation(const char* subject);
  ]]
  local really_useful_string_transformation = ffi.load('...').really_useful_string_transformation
  ngx.say(really_useful_string_transformation("peter"))
```

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately once you dive in to the world of string manipulation FFI tends to get much hairier. Your first example may actually segfault on some platforms as `&str` isn't an FFI-safe type (e.g. it's not equivalent to `const char*`). Returning an owned string (something allocated by Rust) would require some support on the Lua side of things to consume an opaque pointer that it then accessed data through later on, and finally calls the destructor (frees the memory) when you're done with it.

**Comment by alubbe** [comment]
Thanks for your response. Are there any tutorials or resources to read up on for this? Could I use ffi.new in lua to allocate something that rust then passes the string into, and that gets cleaned up by lua?

**Comment by alexcrichton** [comment]
Ah sorry I unfortunately don't know many specifics around Lua so `ffi.new` may or may not work, and I'm also not sure of many tutorials :(

**Comment by alubbe** [comment]
That's unfortunate. Any idea which forums or IRC channels might be able to help me?

**Comment by alexcrichton** [comment]
One of http://users.rust-lang.org/ or `#rust` on the irc.mozilla.org network may be helpful?

**Comment by alubbe** [comment]
http://users.rust-lang.org/ was really helpful, I got it to work. Thanks for your help pointing me in the right direction!
