### ISSUE TITLE
python-to-rust string example needed

### ISSUE THREAD

**Issue by cjwelborn** [alexcrichton/rust-ffi-examples#2]
After two days of searching and asking questions I finally figured out how to make Python talk to Rust using something more than a simple `i32 -> i32` function. No one has a basic example dealing with `String`, `CString`, or `libc::c_char`. I would love to see an example with a function signature kinda like this:
## Rust:

``` rust

extern crate libc;
use libc::{c_char};

#[no_mangle]
pub extern fn say_hello(name: *const c_char) -> *const c_char {
    // ...Handle string from Python,
    //    possibly use the string with Rust libs like Regex or Path..
    //    return a new string built with Rust (preferably in  "safe" manner)
}
```
## Python:

``` python
from cffi import FFI
ffi = FFI()

rustlib = ffi.dlopen('myrustlib.so')

ffi.cdef("""
    char* say_hello(const char *n);
""")

# `myname` could come from anywhere, possibly user arguments.
myname = 'cj'
# Python3, the library is expecting bytes.
name = ffi.new('char[]', bytes(myname, 'utf-8'))

# Again Python3, we'll get bytes back so they need to be decoded.
msg = ffi.string(rustlib.say_hello(name)).decode('utf-8')
print('Rust said: {}'.format(msg))
```

I haven't tested this snippet, but it looks like what I was using. I don't even know if this is the idiomatic way to do this because I'm new to rust/c/c++, but `*const c_char` was the only thing that would work without segfaulting. The problem is I don't know if I am managing memory correctly in my original test library or if there is a better way to achieve the same thing. I'm converting from `*const c_char` to `String` so Rust can display or use the original arguments. `Regex` and `Path` need rust strings to work with.

The [Rust Once, Run Everywhere](http://blog.rust-lang.org/2015/04/24/Rust-Once-Run-Everywhere.html) post showed up right after I tackled this issue on my own. It would be awesome if someone that actually knew what they were doing could write about the use of c strings with Python/Rust.

**Comment by alexcrichton** [comment]
Yeah this is one aspect of FFI I wish I had some more time to explore in the post, but I'm more than happy to help out here! There's two halves to this, so I'll deal with each separately.

First, if you're passing a string from Python into Rust, then the function would probably want to look like this:

``` rust
use std::ffi::CStr;

#[no_mangle]
pub extern fn receive_hello(name: *const c_char) {
    let bytes = unsafe { CStr::from_ptr(name).to_bytes() };
    let name: &str = str::from_utf8(bytes).unwrap(); // make sure the bytes are UTF-8
    // work with `name`
}
```

You can explore the [`CStr` docs](http://doc.rust-lang.org/std/ffi/struct.CStr.html) as well to maybe see some more examples of its usage.

Going in the other direction is somewhat more difficult, however. When crossing language boundaries you need to be wary of memory management. For example is the string returned by Rust owned by Python? Or is it still owned by Rust? It's generally not a good idea for memory allocations to cross the language boundary (e.g. allocated on one side and free'd on another), so you'll probably want Rust to retain ownership of a string or use a separate datatype which has a destructor register in Python to free it on the Rust side.

I'd personally have to read up more on Python's memory management story with respect to FFI to dive a little more into this topics, but does that help?

**Comment by cjwelborn** [comment]
Your input helped me a lot, and maybe this will show up in someone's Google search one day. You confirmed that my method for converting to `&str` \ `String` was not weird (`CStr::from_ptr().to_bytes()`, then `str::from_utf8()`), and the cross-language memory management thing helps. I now know what to look for next (determine what Python does with memory management concerning FFI).

I didn't mean to hold you personally responsible for creating an example/snippet. I've been studying this stuff lately and your blog post presented an opportunity to speak with a real rust-dev about it. I'm sure there will be tons of examples in the near future (good or bad) as Rust interest grows. Thanks for your time.

**Comment by alexcrichton** [comment]
Thanks for the issue! If you figure out how to transfer memory from Rust to Python, I'd be quite interested in learning about this! (especially if it's automatically collected).

After thinking a bit more, one possible solution could be where Rust hands python a `Box<CString>` (e.g. a `*mut CString`) and then there's an accessor which given `*mut CString` returns the contents (e.g. how python reads the value). Finally there'd be a function to free the allocation which would either need to be manually called from Python or registered to be called when the object is GC'd. (maybe at least?)

**Comment by cjwelborn** [comment]
I would have never thought of that. Manually calling it from Python sounds like it would work (even I could manage that implementation), the GC version sounds even better. I'll have to dig in a little bit and see what I come up with.
