### ISSUE TITLE
golang ?

### ISSUE THREAD

**Issue by ghost** [alexcrichton/rust-ffi-examples#20]
I am looking for a good way to do golang to rust FFI both ways.

If anyone has suggestions it would be great. golang is made to call c using cgo, which is very very slow. its golangs fault.
SO thats one way, but perf is really bad.

what else to do to get decent perf and easy of development ?

**Comment by evaporei** [comment]
Have you seen this blog post: https://blog.filippo.io/rustgo/?

**Comment by Antiarchitect** [comment]
Just mentioning https://github.com/alexcrichton/rust-ffi-examples/pull/31

**Comment by Antiarchitect** [comment]
https://github.com/alexcrichton/rust-ffi-examples/pull/32

**Comment by Antiarchitect** [comment]
Seems can be closed.
