### ISSUE TITLE
Rust-to-C : Adding pre compiled archive file

### ISSUE THREAD

**Issue by rowney** [alexcrichton/rust-ffi-examples#7]
Hi,
I see that we can add individual source files, compile those files, create a library and then link it. If we have a huge number of source files then it's bit cumbersome to add individual files.
But for example if I already have an archive file precompiled for a set of C source files then how to link it.

Just for testing, after initial build I replaced libdouble.a with my precompiled archive file with same name and it works. 

So it would be great if there's any way to link already existing static archive. Any suggestions?

Thanks.

**Comment by alexcrichton** [comment]
There is indeed a way to do this! When crates declare that they link to a native library you're then able to [override the build script](http://doc.crates.io/build-script.html#overriding-build-scripts) with your own precompiled version of a library.

**Comment by rowney** [comment]
Yes. This works just fine.
Previously I had tried this procedure but without build.rs. I assumed "override build script" means it does not require build.rs in cargo.toml file.

One more clarification:
`[target.x86_64-unknown-linux-gnu.foo]`
Is it possible to make linking of library `foo` independent of `target`?

Thanks for the quick help.

**Comment by alexcrichton** [comment]
Nah you'll have to provide what platform the library is compiled for (this is how Cargo knows when to use it). This assists in situations where you're cross compiling and you don't want to use the original copy.

In the meantime I think I'm gonna close this issue.

**Comment by rowney** [comment]
Aah..That makes sense. Thanks for clarifying it.
